backend:
  name: git-gateway
  branch: main

# THIS MUST HAVE "public/" so images actually show up on the website
media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page Settings"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
  - name: "gallery"
    label: "Gallery Images"
    # REMOVE "public/" from here! We just want the data files in the root.
    folder: "gallery-data"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Events", "Workshops", "Sports", "Festivals"],
        }
      - { label: "Image", name: "image", widget: "image" }
